--Create cart table
create table CART
(
    id           bigint generated by default as identity,
    created_date timestamp,
    quantity     integer not null,
    product_id   bigint,
    primary key (id)
);
--Create product table
create table PRODUCT
(
    PRODUCT_ID  bigint generated by default as identity,
    productName varchar(255),
    primary key (PRODUCT_ID)
);
--Create seller table
create table SELLER
(
    SELLER_ID  bigint generated by default as identity,
    sellerName varchar(255),
    primary key (SELLER_ID)
);
--Create seller_product table
create table SELLER_PRODUCT
(
    price      numeric(19, 2),
    PRODUCT_ID bigint not null,
    SELLER_ID  bigint not null,
    primary key (PRODUCT_ID, SELLER_ID)
);

alter table CART
    add constraint FK3d704slv66tw6x5hmbm6p2x3u foreign key (product_id) references product;
alter table seller_product
    add constraint FK76egnh07c3r04qmgctr4s5joe foreign key (PRODUCT_ID) references product;
alter table seller_product
    add constraint FKtdg69yn9wlno2l63nvr6vocic foreign key (SELLER_ID) references seller;

INSERT INTO PRODUCT (productName)
VALUES ('aspirina');
INSERT INTO PRODUCT (productName)
VALUES ('jarabe');
INSERT INTO PRODUCT (productName)
VALUES ('fafafa');
INSERT INTO PRODUCT (productName)
VALUES ('vendas');
INSERT INTO SELLER (sellerName)
VALUES ('john');
INSERT INTO SELLER (sellerName)
VALUES ('bill');
INSERT INTO SELLER (sellerName)
VALUES ('steve');
INSERT INTO SELLER_PRODUCT (price, PRODUCT_ID, SELLER_ID)
VALUES (200, 1, 2);
INSERT INTO SELLER_PRODUCT (price, PRODUCT_ID, SELLER_ID)
VALUES (20, 1, 1);

