--Create cart table
create table CART
(
    id           bigint generated by default as identity,
    created_date timestamp,
    quantity     integer not null,
    product_id   bigint,
    primary key (id)
);
--Create product table
create table PRODUCT
(
    id           bigint generated by default as identity,
    product_name varchar(255),
    primary key (id)
);
--Create seller table
create table SELLER
(
    id          bigint generated by default as identity,
    seller_name varchar(255),
    primary key (id)
);

alter table CART
    add constraint FK3d704slv66tw6x5hmbm6p2x3u foreign key (product_id) references product;

INSERT INTO PRODUCT (product_name)
VALUES ('aspirina');
INSERT INTO PRODUCT (product_name)
VALUES ('jarabe');
INSERT INTO SELLER (seller_name)
VALUES ('john');
INSERT INTO SELLER (seller_name)
VALUES ('bill');
INSERT INTO SELLER (seller_name)
VALUES ('steve');



